'key': 'RGAPI-d9001d6d-7b44-47c9-a959-dcbdc38a8a2a'

'CONSUMER_KEY': 'rXBkovNBKIoHkSgrH8N1Fxxhp'
'CONSUMER_SECRET': 'NKyqvhqFZLKELAyYhKAKQBvZWNj21hvaH8czkzVKWOs4ZE0Ewc'
'OAUTH_TOKEN': '840963180868358144-C58nejMrIngcWXHm1wtalnkbmB0CxGr'
'OAUTH_TOKEN_SECRET': 'p1Q3zi1mhkCzr2lpPRzo858G8ldtG0QMToLtkCfltSkU6'
